version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/stunning-robot
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/stunning-robot
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
    mode: 644
    except:
      - .git
